#!/usr/bin/php
<?php

//
// pg - print all PG and PG-13 movies of a given year
//

// include the common PHP code file
require("a2.php");



// PROGRAM BODY BEGINS

$usage = "Usage: $argv[0] Actor";
$db = dbConnect(DB_CONNECTION);

// Check arguments
if (count($argv) < 2) exit("$usage\n");

// Get the return results
$actor = strtolower($argv[1]);
$q = "select * from actors_movie where LOWER(actor) = '$actor' order by year;";
$r = dbQuery($db, mkSQL($q, $actor));

// Iterate through the results and print
$i = 1;
while ($t = dbNext($r)) {
  if(empty($t[2]) && empty($t[3]) && empty($t[4])){
  	echo "$i. $t[0] -- $t[1]";
  	return;
  }
  echo "$i. $t[0] -- $t[1](";
  if (!empty($t[2]))
    echo "$t[2], ";
  if (!empty($t[3]))
      echo "$t[3], ";
  if(!empty($t[4]))
  	  echo "$t[4]";
  echo ")\n";
  $i++;
}

?>
